// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vdb/Detail.html:2
package vdb

//line views/vdb/Detail.html:2
import (
	"github.com/kyleu/dbaudit/app"
	"github.com/kyleu/dbaudit/app/controller/cutil"
	"github.com/kyleu/dbaudit/app/db"
	"github.com/kyleu/dbaudit/views/components"
	"github.com/kyleu/dbaudit/views/components/view"
	"github.com/kyleu/dbaudit/views/layout"
)

//line views/vdb/Detail.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vdb/Detail.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vdb/Detail.html:11
type Detail struct {
	layout.Basic
	Model *db.Connection
}

//line views/vdb/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vdb/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-connection"><button type="button">`)
//line views/vdb/Detail.html:19
	components.StreamSVGRef(qw422016, "file", 15, 15, "icon", ps)
//line views/vdb/Detail.html:19
	qw422016.N().S(`JSON</button></a>
      <a href="`)
//line views/vdb/Detail.html:20
	qw422016.E().S(p.Model.WebPath())
//line views/vdb/Detail.html:20
	qw422016.N().S(`/edit"><button>`)
//line views/vdb/Detail.html:20
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vdb/Detail.html:20
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vdb/Detail.html:22
	components.StreamSVGRefIcon(qw422016, `database`, ps)
//line views/vdb/Detail.html:22
	qw422016.N().S(` `)
//line views/vdb/Detail.html:22
	qw422016.E().S(p.Model.TitleString())
//line views/vdb/Detail.html:22
	qw422016.N().S(`</h3>
    <div><a href="/db"><em>Connection</em></a></div>
    <div class="mt overflow full-width">
      <table>
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vdb/Detail.html:29
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vdb/Detail.html:29
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Name</th>
            <td><strong>`)
//line views/vdb/Detail.html:33
	view.StreamString(qw422016, p.Model.Name)
//line views/vdb/Detail.html:33
	qw422016.N().S(`</strong></td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Icon</th>
            <td>`)
//line views/vdb/Detail.html:37
	view.StreamString(qw422016, p.Model.Icon)
//line views/vdb/Detail.html:37
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="`)
//line views/vdb/Detail.html:40
	qw422016.E().S(db.AllEngines.Help())
//line views/vdb/Detail.html:40
	qw422016.N().S(`">Engine</th>
            <td>`)
//line views/vdb/Detail.html:41
	qw422016.E().S(p.Model.Engine.String())
//line views/vdb/Detail.html:41
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Server</th>
            <td>`)
//line views/vdb/Detail.html:45
	view.StreamString(qw422016, p.Model.Server)
//line views/vdb/Detail.html:45
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Integer">Port</th>
            <td>`)
//line views/vdb/Detail.html:49
	qw422016.N().D(p.Model.Port)
//line views/vdb/Detail.html:49
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Username</th>
            <td>`)
//line views/vdb/Detail.html:53
	view.StreamString(qw422016, p.Model.Username)
//line views/vdb/Detail.html:53
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Password</th>
            <td>`)
//line views/vdb/Detail.html:57
	view.StreamString(qw422016, p.Model.Password)
//line views/vdb/Detail.html:57
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Database</th>
            <td>`)
//line views/vdb/Detail.html:61
	view.StreamString(qw422016, p.Model.Database)
//line views/vdb/Detail.html:61
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Schema</th>
            <td>`)
//line views/vdb/Detail.html:65
	view.StreamString(qw422016, p.Model.Schema)
//line views/vdb/Detail.html:65
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Conn Override</th>
            <td>`)
//line views/vdb/Detail.html:69
	view.StreamString(qw422016, p.Model.ConnOverride)
//line views/vdb/Detail.html:69
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vdb/Detail.html:76
	qw422016.N().S(`  `)
//line views/vdb/Detail.html:77
	components.StreamJSONModal(qw422016, "connection", "Connection JSON", p.Model, 1)
//line views/vdb/Detail.html:77
	qw422016.N().S(`
`)
//line views/vdb/Detail.html:78
}

//line views/vdb/Detail.html:78
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vdb/Detail.html:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vdb/Detail.html:78
	p.StreamBody(qw422016, as, ps)
//line views/vdb/Detail.html:78
	qt422016.ReleaseWriter(qw422016)
//line views/vdb/Detail.html:78
}

//line views/vdb/Detail.html:78
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vdb/Detail.html:78
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vdb/Detail.html:78
	p.WriteBody(qb422016, as, ps)
//line views/vdb/Detail.html:78
	qs422016 := string(qb422016.B)
//line views/vdb/Detail.html:78
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vdb/Detail.html:78
	return qs422016
//line views/vdb/Detail.html:78
}
