// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vdb/Table.html:2
package vdb

//line views/vdb/Table.html:2
import (
	"github.com/kyleu/dbaudit/app"
	"github.com/kyleu/dbaudit/app/controller/cutil"
	"github.com/kyleu/dbaudit/app/db"
	"github.com/kyleu/dbaudit/app/lib/filter"
	"github.com/kyleu/dbaudit/views/components"
	"github.com/kyleu/dbaudit/views/components/view"
)

//line views/vdb/Table.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vdb/Table.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vdb/Table.html:11
func StreamTable(qw422016 *qt422016.Writer, models db.Connections, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vdb/Table.html:11
	qw422016.N().S(`
`)
//line views/vdb/Table.html:12
	prms := params.Sanitized("db", ps.Logger)

//line views/vdb/Table.html:12
	qw422016.N().S(`  <table>
    <thead>
      <tr>
        `)
//line views/vdb/Table.html:16
	components.StreamTableHeaderSimple(qw422016, "db", "id", "ID", "UUID in format (00000000-0000-0000-0000-000000000000)", prms, ps.URI, ps)
//line views/vdb/Table.html:16
	qw422016.N().S(`
        `)
//line views/vdb/Table.html:17
	components.StreamTableHeaderSimple(qw422016, "db", "name", "Name", "String text", prms, ps.URI, ps)
//line views/vdb/Table.html:17
	qw422016.N().S(`
        `)
//line views/vdb/Table.html:18
	components.StreamTableHeaderSimple(qw422016, "db", "icon", "Icon", "String text", prms, ps.URI, ps)
//line views/vdb/Table.html:18
	qw422016.N().S(`
        `)
//line views/vdb/Table.html:19
	components.StreamTableHeaderSimple(qw422016, "db", "engine", "Engine", db.AllEngines.Help(), prms, ps.URI, ps)
//line views/vdb/Table.html:19
	qw422016.N().S(`
        `)
//line views/vdb/Table.html:20
	components.StreamTableHeaderSimple(qw422016, "db", "server", "Server", "String text", prms, ps.URI, ps)
//line views/vdb/Table.html:20
	qw422016.N().S(`
        `)
//line views/vdb/Table.html:21
	components.StreamTableHeaderSimple(qw422016, "db", "database", "Database", "String text", prms, ps.URI, ps)
//line views/vdb/Table.html:21
	qw422016.N().S(`
      </tr>
    </thead>
    <tbody>
`)
//line views/vdb/Table.html:25
	for _, model := range models {
//line views/vdb/Table.html:25
		qw422016.N().S(`      <tr>
        <td><a href="/db/`)
//line views/vdb/Table.html:27
		view.StreamUUID(qw422016, &model.ID)
//line views/vdb/Table.html:27
		qw422016.N().S(`">`)
//line views/vdb/Table.html:27
		view.StreamUUID(qw422016, &model.ID)
//line views/vdb/Table.html:27
		qw422016.N().S(`</a></td>
        <td><strong>`)
//line views/vdb/Table.html:28
		view.StreamString(qw422016, model.Name)
//line views/vdb/Table.html:28
		qw422016.N().S(`</strong></td>
        <td>`)
//line views/vdb/Table.html:29
		view.StreamString(qw422016, model.Icon)
//line views/vdb/Table.html:29
		qw422016.N().S(`</td>
        <td>`)
//line views/vdb/Table.html:30
		qw422016.E().S(model.Engine.String())
//line views/vdb/Table.html:30
		qw422016.N().S(`</td>
        <td>`)
//line views/vdb/Table.html:31
		view.StreamString(qw422016, model.Server)
//line views/vdb/Table.html:31
		qw422016.N().S(`</td>
        <td>`)
//line views/vdb/Table.html:32
		view.StreamString(qw422016, model.Database)
//line views/vdb/Table.html:32
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vdb/Table.html:34
	}
//line views/vdb/Table.html:35
	if prms.HasNextPage(len(models)+prms.Offset) || prms.HasPreviousPage() {
//line views/vdb/Table.html:35
		qw422016.N().S(`      <tr>
        <td colspan="6">`)
//line views/vdb/Table.html:37
		components.StreamPagination(qw422016, len(models)+prms.Offset, prms, ps.URI)
//line views/vdb/Table.html:37
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vdb/Table.html:39
	}
//line views/vdb/Table.html:39
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vdb/Table.html:42
}

//line views/vdb/Table.html:42
func WriteTable(qq422016 qtio422016.Writer, models db.Connections, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vdb/Table.html:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vdb/Table.html:42
	StreamTable(qw422016, models, params, as, ps)
//line views/vdb/Table.html:42
	qt422016.ReleaseWriter(qw422016)
//line views/vdb/Table.html:42
}

//line views/vdb/Table.html:42
func Table(models db.Connections, params filter.ParamSet, as *app.State, ps *cutil.PageState) string {
//line views/vdb/Table.html:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vdb/Table.html:42
	WriteTable(qb422016, models, params, as, ps)
//line views/vdb/Table.html:42
	qs422016 := string(qb422016.B)
//line views/vdb/Table.html:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vdb/Table.html:42
	return qs422016
//line views/vdb/Table.html:42
}
