// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vstatement/Edit.html:2
package vstatement

//line views/vstatement/Edit.html:2
import (
	"github.com/kyleu/dbaudit/app"
	"github.com/kyleu/dbaudit/app/controller/cutil"
	"github.com/kyleu/dbaudit/app/statement"
	"github.com/kyleu/dbaudit/app/util"
	"github.com/kyleu/dbaudit/views/components"
	"github.com/kyleu/dbaudit/views/components/edit"
	"github.com/kyleu/dbaudit/views/layout"
)

//line views/vstatement/Edit.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vstatement/Edit.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vstatement/Edit.html:12
type Edit struct {
	layout.Basic
	Model *statement.Statement
	IsNew bool
}

//line views/vstatement/Edit.html:18
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstatement/Edit.html:18
	qw422016.N().S(`
  <div class="card">
`)
//line views/vstatement/Edit.html:20
	if p.IsNew {
//line views/vstatement/Edit.html:20
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vstatement/Edit.html:22
		components.StreamSVGRefIcon(qw422016, `database`, ps)
//line views/vstatement/Edit.html:22
		qw422016.N().S(` New Statement</h3>
    <form action="/statement/_new" class="mt" method="post">
`)
//line views/vstatement/Edit.html:24
	} else {
//line views/vstatement/Edit.html:24
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vstatement/Edit.html:25
		qw422016.E().S(p.Model.WebPath())
//line views/vstatement/Edit.html:25
		qw422016.N().S(`/delete" onclick="return confirm('Are you sure you wish to delete statement [`)
//line views/vstatement/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vstatement/Edit.html:25
		qw422016.N().S(`]?')"><button>Delete</button></a></div>
    <h3>`)
//line views/vstatement/Edit.html:26
		components.StreamSVGRefIcon(qw422016, `database`, ps)
//line views/vstatement/Edit.html:26
		qw422016.N().S(` Edit Statement [`)
//line views/vstatement/Edit.html:26
		qw422016.E().S(p.Model.String())
//line views/vstatement/Edit.html:26
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vstatement/Edit.html:28
	}
//line views/vstatement/Edit.html:28
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vstatement/Edit.html:31
	if p.IsNew {
//line views/vstatement/Edit.html:31
		edit.StreamUUIDTable(qw422016, "id", "", "ID", &p.Model.ID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vstatement/Edit.html:31
	}
//line views/vstatement/Edit.html:31
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:32
	edit.StreamIntTable(qw422016, "sessionID", "", "Session ID", p.Model.SessionID, 5, "Integer")
//line views/vstatement/Edit.html:32
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:33
	edit.StreamSelectTable(qw422016, "action", "", "Action", p.Model.Action.Key, statement.AllActions.Keys(), statement.AllActions.Strings(), 5, statement.AllActions.Help())
//line views/vstatement/Edit.html:33
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:34
	edit.StreamBoolTable(qw422016, "succeeded", "Succeeded", p.Model.Succeeded, 5, "Value [true] or [false]")
//line views/vstatement/Edit.html:34
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:35
	edit.StreamStringTable(qw422016, "principal", "", "Principal", p.Model.Principal, 5, "String text")
//line views/vstatement/Edit.html:35
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:36
	edit.StreamStringTable(qw422016, "database", "", "Database", p.Model.Database, 5, "String text")
//line views/vstatement/Edit.html:36
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:37
	edit.StreamStringTable(qw422016, "filename", "", "Filename", p.Model.Filename, 5, "String text")
//line views/vstatement/Edit.html:37
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:38
	edit.StreamStringTable(qw422016, "host", "", "Host", p.Model.Host, 5, "String text")
//line views/vstatement/Edit.html:38
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:39
	edit.StreamIntTable(qw422016, "transactionID", "", "Transaction ID", p.Model.TransactionID, 5, "Integer")
//line views/vstatement/Edit.html:39
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:40
	edit.StreamStringTable(qw422016, "clientIP", "", "Client IP", p.Model.ClientIP, 5, "String text")
//line views/vstatement/Edit.html:40
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:41
	edit.StreamIntTable(qw422016, "duration", "", "Duration", p.Model.Duration, 5, "Integer")
//line views/vstatement/Edit.html:41
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:42
	edit.StreamUUIDTable(qw422016, "connectionID", "", "Connection ID", &p.Model.ConnectionID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vstatement/Edit.html:42
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:43
	edit.StreamIntTable(qw422016, "rowsAffected", "", "Rows Affected", p.Model.RowsAffected, 5, "Integer")
//line views/vstatement/Edit.html:43
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:44
	edit.StreamIntTable(qw422016, "rowsReturned", "", "Rows Returned", p.Model.RowsReturned, 5, "Integer")
//line views/vstatement/Edit.html:44
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:45
	edit.StreamTextareaTable(qw422016, "sql", "", "SQL", 8, p.Model.SQL, 5, "String text")
//line views/vstatement/Edit.html:45
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:46
	edit.StreamTextareaTable(qw422016, "types", "", "Types", 8, util.ToJSON(p.Model.Types), 5, "JSON object")
//line views/vstatement/Edit.html:46
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:47
	edit.StreamTextareaTable(qw422016, "values", "", "Values", 8, util.ToJSON(p.Model.Values), 5, "JSON object")
//line views/vstatement/Edit.html:47
	qw422016.N().S(`
          `)
//line views/vstatement/Edit.html:48
	edit.StreamTimestampTable(qw422016, "occurred", "", "Occurred", &p.Model.Occurred, 5, "Date and time, in almost any format")
//line views/vstatement/Edit.html:48
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vstatement/Edit.html:54
}

//line views/vstatement/Edit.html:54
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstatement/Edit.html:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vstatement/Edit.html:54
	p.StreamBody(qw422016, as, ps)
//line views/vstatement/Edit.html:54
	qt422016.ReleaseWriter(qw422016)
//line views/vstatement/Edit.html:54
}

//line views/vstatement/Edit.html:54
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vstatement/Edit.html:54
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vstatement/Edit.html:54
	p.WriteBody(qb422016, as, ps)
//line views/vstatement/Edit.html:54
	qs422016 := string(qb422016.B)
//line views/vstatement/Edit.html:54
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vstatement/Edit.html:54
	return qs422016
//line views/vstatement/Edit.html:54
}
