// Code generated by qtc from "types.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/types.sql:2
package ddl

//line queries/ddl/types.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/types.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/types.sql:2
func StreamTypesDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/types.sql:2
	qw422016.N().S(`
-- `)
//line queries/ddl/types.sql:3
}

//line queries/ddl/types.sql:3
func WriteTypesDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/types.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/types.sql:3
	StreamTypesDrop(qw422016)
//line queries/ddl/types.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/types.sql:3
}

//line queries/ddl/types.sql:3
func TypesDrop() string {
//line queries/ddl/types.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/types.sql:3
	WriteTypesDrop(qb422016)
//line queries/ddl/types.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/types.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/types.sql:3
	return qs422016
//line queries/ddl/types.sql:3
}

// --

//line queries/ddl/types.sql:5
func StreamTypesCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/types.sql:5
	qw422016.N().S(`
-- skipping definition of enum [action], since SQL Server does not support custom types
-- skipping definition of enum [engine], since SQL Server does not support custom types
-- `)
//line queries/ddl/types.sql:8
}

//line queries/ddl/types.sql:8
func WriteTypesCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/types.sql:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/types.sql:8
	StreamTypesCreate(qw422016)
//line queries/ddl/types.sql:8
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/types.sql:8
}

//line queries/ddl/types.sql:8
func TypesCreate() string {
//line queries/ddl/types.sql:8
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/types.sql:8
	WriteTypesCreate(qb422016)
//line queries/ddl/types.sql:8
	qs422016 := string(qb422016.B)
//line queries/ddl/types.sql:8
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/types.sql:8
	return qs422016
//line queries/ddl/types.sql:8
}
