// Code generated by qtc from "createDatabase.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/schema/createDatabase.sql:1
package schema

//line queries/schema/createDatabase.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/schema/createDatabase.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/schema/createDatabase.sql:1
func StreamCreateDatabase(qw422016 *qt422016.Writer) {
//line queries/schema/createDatabase.sql:1
	qw422016.N().S(`
create role "dbaudit" with login password 'dbaudit';

create database "dbaudit";
alter database "dbaudit" set timezone to 'utc';
grant all privileges on database "dbaudit" to "dbaudit";
-- `)
//line queries/schema/createDatabase.sql:7
}

//line queries/schema/createDatabase.sql:7
func WriteCreateDatabase(qq422016 qtio422016.Writer) {
//line queries/schema/createDatabase.sql:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/schema/createDatabase.sql:7
	StreamCreateDatabase(qw422016)
//line queries/schema/createDatabase.sql:7
	qt422016.ReleaseWriter(qw422016)
//line queries/schema/createDatabase.sql:7
}

//line queries/schema/createDatabase.sql:7
func CreateDatabase() string {
//line queries/schema/createDatabase.sql:7
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/schema/createDatabase.sql:7
	WriteCreateDatabase(qb422016)
//line queries/schema/createDatabase.sql:7
	qs422016 := string(qb422016.B)
//line queries/schema/createDatabase.sql:7
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/schema/createDatabase.sql:7
	return qs422016
//line queries/schema/createDatabase.sql:7
}
