// Code generated by qtc from "SizeInfo.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/schema/SizeInfo.sql:2
package schema

//line queries/schema/SizeInfo.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/schema/SizeInfo.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/schema/SizeInfo.sql:2
func StreamSizeInfo(qw422016 *qt422016.Writer, dbType string) {
//line queries/schema/SizeInfo.sql:2
	qw422016.N().S(`
-- `)
//line queries/schema/SizeInfo.sql:3
	switch dbType {
	// --

//line queries/schema/SizeInfo.sql:4
	case "sqlserver":
//line queries/schema/SizeInfo.sql:4
		qw422016.N().S(`
select 'TODO';
-- `)
//line queries/schema/SizeInfo.sql:6
	default:
//line queries/schema/SizeInfo.sql:6
		qw422016.N().S(`
select 'unhandled database type [`)
//line queries/schema/SizeInfo.sql:7
		qw422016.E().S(dbType)
//line queries/schema/SizeInfo.sql:7
		qw422016.N().S(`]';
-- `)
//line queries/schema/SizeInfo.sql:8
	}
//line queries/schema/SizeInfo.sql:8
	qw422016.N().S(`
-- `)
//line queries/schema/SizeInfo.sql:9
}

//line queries/schema/SizeInfo.sql:9
func WriteSizeInfo(qq422016 qtio422016.Writer, dbType string) {
//line queries/schema/SizeInfo.sql:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/schema/SizeInfo.sql:9
	StreamSizeInfo(qw422016, dbType)
//line queries/schema/SizeInfo.sql:9
	qt422016.ReleaseWriter(qw422016)
//line queries/schema/SizeInfo.sql:9
}

//line queries/schema/SizeInfo.sql:9
func SizeInfo(dbType string) string {
//line queries/schema/SizeInfo.sql:9
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/schema/SizeInfo.sql:9
	WriteSizeInfo(qb422016, dbType)
//line queries/schema/SizeInfo.sql:9
	qs422016 := string(qb422016.B)
//line queries/schema/SizeInfo.sql:9
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/schema/SizeInfo.sql:9
	return qs422016
//line queries/schema/SizeInfo.sql:9
}
